### ISSUE TITLE
Requirements versions

### ISSUE THREAD

**Issue by juanb001** [Xinglab/CLAM#12]
Hi again,

I was having issues running permutation_peakcaller for the longest time, but I think I figured out the issues, since the function started running this time. I originally installed all the latest dependencies in your "Requirements" file that were available for python 2.7.16 (since permutation_peakcaller currently only works with python2 and not python3, from what I can tell in the other issue post) on OSX 10.14.6. However, when I tried running the peakcaller function, I would get an error regarding numpy not having an attribute "_version_". From other forums, this might happen when there are extra "numpy.py" files. There was one of these files in one of the statsmodels directories; deleting this got around the attribute issue, but brought a new issue about no module name "pandas.util._decorators." From the pandas changelog, this was made a private function as of 0.20.0. Earlier versions of pandas are not compatible with the latest version of statsmodels.

Ultimately, I installed pandas==0.19.2 and statsmodel==0.10.2 and this allowed the program to run. I will see later if it runs to completion! It would be nice if you listed which versions of the required dependencies you are running, as it seems the latest versions do not currently work well together (at least on my computer). Thank you!

**Comment by wkdeng** [comment]
Thanks a lot for your update!
