### ISSUE TITLE
question in software

### ISSUE THREAD

**Issue by Golden-proteogenomics** [Xinglab/CLAM#20]
For the one question, I want to know this software could analyze Par-clip data, the other question is what you use the star software to mapping ref genome, which will discard some short reads, how to deal with it?

**Comment by zj-zhang** [comment]
For Par-clip, the best strategy is to tag the induced mutation locus for each read, and perform peak calling using the reads preprocessed afterwards. This feature is in the TO-DO plan to be implemented; though not ideal, using other read tagging methods like "median" will also work for a lot of cases. Please checkout our documentation here: https://github.com/Xinglab/CLAM#section41

CLAM calls peaks on a BAM file regardless of which software is used to generate the BAM. You can use other aligners that are more short-read sensitive, such as Novoalign, the software we used in the original CLAM paper published in NAR. Our tutorial outlines STAR as aligner to keep consistency with the eCLIP SOP but CLAM is not restricted to STAR.

**Comment by Golden-proteogenomics** [comment]
Ok, thanks for your help and understanding of this software. However, I want to know if CLAM could like the Hommer to call peak and produce a file for IGV or UCSC browser to view?

**Comment by zj-zhang** [comment]
You can use the command-line interface `bedToBigBed` in the USCS toolbox to easily convert CLAM's bed file to bigBed for visualization in IGC or UCSC.
https://genome.ucsc.edu/goldenPath/help/bigBed.html
https://bioconda.github.io/recipes/ucsc-bedtobigbed/README.html

**Comment by Golden-proteogenomics** [comment]
OK, thanks.
