### ISSUE TITLE
Clarification on parameters

### ISSUE THREAD

**Issue by juanb001** [Xinglab/CLAM#9]
Hello,

Would it be possible to update the documentation/readme with a short description for the different parameters (ie. what do the "read-tagger-method", "--max-tags", etc parameters do or change)? I've looked through the provided files and didn't see this, but maybe I missed this?

Thank you!

**Comment by zj-zhang** [comment]
Hi @juanb001 
Thanks for pointing this out. 
```--read-tagger-method``` will tag a CLIP/RIP read to a particular locus; 'median' tags read center and is recommended for RIP-seq; 'start' tags read start site and is recommended for CLIP-seq.
```--max-tags N``` will collapse reads mapped to the identical locations up to N reads. This is usually used for RIP-seq with strong PCR duplication issues.

@wkdeng Please feel free to comment on the documentation :)

**Comment by juanb001** [comment]
Thanks for the clarification and looking forward to the updated documentation!

**Comment by juanb001** [comment]
I saw that descriptions for "read-tagger-method" and "max-tags" are now included, thanks! Would you also let me know what the "--normalize-lib" and "--pool" parameters for permutation_callpeak do? I assume --normalize-lib normalizes each alignment so that sequencing depths are relatively the same; is that correct, and would you recommend running the function with that parameter enabled?

A related question, I know you can enter replicates with the peakcaller function; is this also possible with the permutation_callpeak function?

Thank you!

**Comment by 1409605824** [comment]
> Hi @juanb001
> Thanks for pointing this out.
> `--read-tagger-method` will tag a CLIP/RIP read to a particular locus; 'median' tags read center and is recommended for RIP-seq; 'start' tags read start site and is recommended for CLIP-seq.
> `--max-tags N` will collapse reads mapped to the identical locations up to N reads. This is usually used for RIP-seq with strong PCR duplication issues.
> 
> @wkdeng Please feel free to comment on the documentation :)

**Comment by wkdeng** [comment]
This two parameters were renamed, see new --help for more information.
